// Generated by CoffeeScript 1.7.1
(function() {
  var lookup, request, zlib;

  request = require('request');

  zlib = require('zlib');

  lookup = function(type, id, callback) {
    var req;
    req = request.post('http://tribunal.uc.edu/attendance/ajax/lookup', {
      form: {
        type: type,
        id: id
      },
      headers: {
        'X-Requested-With': 'XMLHttpRequest',
        'Accept-Encoding': 'gzip'
      },
      encoding: null
    });
    return req.on('response', function(res) {
      var chunks;
      chunks = [];
      res.on('data', function(chunk) {
        return chunks.push(chunk);
      });
      return res.on('end', function() {
        var buffer;
        buffer = Buffer.concat(chunks);
        return zlib.gunzip(buffer, function(err, decoded) {
          var data;
          data = JSON.parse(decoded.toString());
          err = err || data.err;
          return callback(err, data);
        });
      });
    });
  };

  exports.lookupByIso = function(iso, callback) {
    return lookup('iso', iso, callback);
  };

  exports.lookupByUcid = function(ucid, callback) {
    return lookup('ucid', ucid, callback);
  };

}).call(this);
